### search users
GET http://localhost:8082/internal/users/search?status=active
X-Public: false


### users login
POST http://localhost:8082/users/login
content-type: application/json

{
    "email" : "romdoni@email.com",
    "password" : "password"
}


### get user by user_id
GET http://localhost:8082/users/3
X-Public: false


### create new users
POST http://localhost:8082/users
content-type: application/json

{
    "first_name" : "Romdoni",
    "last_name" : "Agung",
    "email" : "romdoni@email.com",
    "password" : "password"
}


### update user by id
PUT http://localhost:8082/users/3
content-type: application/json

{
    "first_name" : "Romdoni",
    "last_name" : "Agung",
    "email" : "romdoni@email.com",
    "password" : "updated_password"
}


### delete user by user_id
DELETE http://localhost:8082/users/1
